
spring:
  servlet:
    multipart:
      max-file-size: 200MB

      max-request-size: 200MB
  jpa:
    open-in-view: false



  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/cfft
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: beans
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

